import turtle as trtl
sauce = trtl.Turtle()
class Ending:
  def __init__(self):
      global sauce
      sauce = trtl.Turtle()
      global zoy
      zoy = trtl.Turtle()
      

  def badEnding(self):
    trtl.bgcolor("#c33f3c")
    sauce.speed(0)
    sauce.penup()
    sauce.setposition(-60,-50)
    sauce.pendown()
    sauce.begin_fill()
    sauce.fillcolor("#d9dad7")
    sauce.forward(100)
    sauce.circle(20,90)
    sauce.forward(200)
    sauce.circle(20,90)
    sauce.forward(100)
    sauce.circle(20,90)
    sauce.forward(200)
    sauce.circle(20,90)
    sauce.end_fill()
    sauce.penup()
    sauce.setposition(-60,-31)
    sauce.begin_fill()
    sauce.fillcolor("gray")
    sauce.pendown()
    sauce.forward(105)
    sauce.left(90)
    sauce.forward(200)
    sauce.left(90)
    sauce.forward(110)
    sauce.left(90)
    sauce.forward(200)
    sauce.left(90)
    sauce.forward(5)
    sauce.end_fill()
    sauce.penup()
    sauce.setposition(-10,-47)
    sauce.begin_fill()
    sauce.color("black")
    sauce.circle(7)
    sauce.end_fill()
    sauce.penup()
    sauce.setposition(-17,175)
    sauce.begin_fill()
    sauce.color("black")
    sauce.circle(3)
    sauce.end_fill()
    sauce.penup()
    sauce.setposition(-17,177)
    sauce.forward(5)
    sauce.pendown()
    sauce.pensize(2)
    sauce.forward(20)
    sauce.penup()
    sauce.setposition(-10,167)
    sauce.pendown()
    sauce.right(25)
    sauce.forward(30)
    sauce.right(90)
    sauce.forward(50)
    sauce.left(37)
    sauce.forward(14)
    sauce.right(121)
    sauce.forward(20)
    sauce.left(124)
    sauce.forward(30)
    sauce.right(78)
    sauce.forward(20)
    sauce.left(90)
    sauce.forward(50)
    sauce.right(79)
    sauce.forward(30)
    sauce.left(108)
    sauce.forward(40)
    sauce.right(70)
    sauce.forward(10)
    sauce.hideturtle()


  def goodEnding(self):
    trtl.bgcolor("#3cc34e")
    zoy.speed(0)
    zoy.penup()
    zoy.setposition(-80,-50)
    zoy.pendown()
    zoy.begin_fill()
    zoy.fillcolor("#d9dad7")
    zoy.forward(100)
    zoy.circle(20,90)
    zoy.forward(200)
    zoy.circle(20,90)
    zoy.forward(100)
    zoy.circle(20,90)
    zoy.forward(200)
    zoy.circle(20,90)
    zoy.end_fill()
    zoy.penup()
    zoy.setposition(-80,-31)
    zoy.begin_fill()
    zoy.fillcolor("gray")
    zoy.pendown()
    zoy.forward(105)
    zoy.left(90)
    zoy.forward(200)
    zoy.left(90)
    zoy.forward(110)
    zoy.left(90)
    zoy.forward(200)
    zoy.left(90)
    zoy.forward(5)
    zoy.penup()
    zoy.end_fill()
    zoy.setposition(-30,-47)
    zoy.begin_fill()
    zoy.color("black")
    zoy.circle(7)
    zoy.end_fill()
    zoy.penup()
    zoy.setposition(-37,175)
    zoy.begin_fill()
    zoy.color("black")
    zoy.circle(3)
    zoy.end_fill()
    zoy.penup()
    zoy.setposition(-37,177)
    zoy.forward(5)
    zoy.pendown()
    zoy.pensize(2)
    zoy.forward(20)
    zoy.hideturtle()



