import turtle as trtl
zoy = trtl.Turtle()
wn=trtl.Screen()
wn.setup(800,600)

trtl.bgcolor("#3cc34e")
def good_ending():
  zoy.speed(0)
  zoy.penup()
  zoy.setposition(-80,-50)
  zoy.pendown()
  zoy.begin_fill()
  zoy.fillcolor("#d9dad7")
  zoy.forward(100)
  zoy.circle(20,90)
  zoy.forward(200)
  zoy.circle(20,90)
  zoy.forward(100)
  zoy.circle(20,90)
  zoy.forward(200)
  zoy.circle(20,90)
  zoy.end_fill()
  zoy.penup()
  zoy.setposition(-80,-31)
  zoy.begin_fill()
  zoy.fillcolor("gray")
  zoy.pendown()
  zoy.forward(105)
  zoy.left(90)
  zoy.forward(200)
  zoy.left(90)
  zoy.forward(110)
  zoy.left(90)
  zoy.forward(200)
  zoy.left(90)
  zoy.forward(5)
  zoy.penup()
  zoy.end_fill()
  zoy.setposition(-30,-47)
  zoy.begin_fill()
  zoy.color("black")
  zoy.circle(7)
  zoy.end_fill()
  zoy.penup()
  zoy.setposition(-37,175)
  zoy.begin_fill()
  zoy.color("black")
  zoy.circle(3)
  zoy.end_fill()
  zoy.penup()
  zoy.setposition(-37,177)
  zoy.forward(5)
  zoy.pendown()
  zoy.pensize(2)
  zoy.forward(20)
  zoy.hideturtle()

good_ending()

wn = trtl.Screen()
wn.mainloop()
